"""常量定义"""
DOMAIN = "hotwater_switch"
CONF_ACCESS_TOKEN = "access_token"
CONF_USER_ID = "user_id"
CONF_FAMILY_ID = "family_id"

DEFAULT_NAME = "HotWater Heater"
DEFAULT_DEVICE_ID = "YOUR_DEVICE_ID"
DEFAULT_PRODUCT_TYPE = "21"
DEFAULT_DEVICE_TYPE = "DR1600HF1"
